### ISSUE TITLE
Search bar shrunk on Safari

### ISSUE THREAD

**Issue by joshrap-eb** [mrin9/RapiDoc#425]
One of our teammates noticed on safari the search bar is shrunk and is practically impossible to click. 
![Capture](https://user-images.githubusercontent.com/74060233/109048141-bba81100-76a4-11eb-8cd8-00eaaa0c5ae7.PNG)

This is what it normally looks like
![Capture](https://user-images.githubusercontent.com/74060233/109048239-d9757600-76a4-11eb-97a8-dee5ab0a40e6.PNG)

She told me that it does work on her Chrome, so it looks like its just a Safari problem. I just recently replicated it on a VM using safari. We are using version 8.4.8 of RapiDoc.

**Comment by mrin9** [comment]
I tested with safari v-14.0.3. I was not able to recreate the issue on my end.
However i fixed some styling around the search bar. can you give it a try using the build from `./dist/rapidoc-min.js` and let me know ?

**Comment by joshrap-eb** [comment]
I'm using this on my script 
` <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>`
And the issue is still there. I'm emulating it on Browserstack so its using the latest version of Safari for me.

**Comment by mrin9** [comment]
> I'm using this on my script
> <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>

That will not give you the latest (_non-released_) build

But, i was able to recreate the issue and will provide a fix shortly.
Thank you for taking time to test and report it

**Comment by joshrap-eb** [comment]
Oh my bad, how do i get the latest non released build? I'm still learning how to use js lol I'm usually a backend developer.

**Comment by mrin9** [comment]
you need to pick `rapidoc-min.js` from this repo's `dist` folder.
https://github.com/mrin9/RapiDoc/blob/master/dist/rapidoc-min.js
store it somewhere on your server,  and then access it from there 

or you can directly access it from  github website (test if you like the download speed)
```html
<script type="module" src="https://raw.githubusercontent.com/mrin9/RapiDoc/master/dist/rapidoc-min.js"></script>
```

> we do not guarantee availability of non-released build all the time or recommend using a non-release build in production
